"""
Stock screener and side-by-side comparison.

Both run against the cached `security_metrics` snapshot.

A filtering rule worth stating: a company whose metric is unknown is EXCLUDED
from a filter on that metric, never treated as zero. Treating a missing ROE as
0% would silently hide companies from a "ROE above 15%" screen for the wrong
reason, and treating it as a pass would put unmeasured companies in a list the
user believes is measured. The result set therefore always reports how many
companies were skipped for missing data.
"""
from __future__ import annotations

from sqlalchemy import select

from ..models import Security, SecurityMetrics

# field -> (column, human label, unit)
FILTERABLE = {
    "market_cap": ("market_cap", "Market value", "EGP"),
    "pe": ("pe", "Price / earnings", "x"),
    "pb": ("pb", "Price / book", "x"),
    "ps": ("ps", "Price / sales", "x"),
    "ev_ebitda": ("ev_ebitda", "EV / EBITDA", "x"),
    "dividend_yield_pct": ("dividend_yield_pct", "Dividend yield", "%"),
    "roe_pct": ("roe_pct", "Return on equity", "%"),
    "roa_pct": ("roa_pct", "Return on assets", "%"),
    "roic_pct": ("roic_pct", "Return on invested capital", "%"),
    "net_margin_pct": ("net_margin_pct", "Net margin", "%"),
    "operating_margin_pct": ("operating_margin_pct", "Operating margin", "%"),
    "revenue_growth_pct": ("revenue_growth_pct", "Revenue growth", "%"),
    "revenue_cagr_3y_pct": ("revenue_cagr_3y_pct", "Revenue growth (3y)", "%"),
    "earnings_growth_pct": ("earnings_growth_pct", "Profit growth", "%"),
    "debt_to_equity": ("debt_to_equity", "Debt / equity", "x"),
    "adtv_90d": ("adtv_90d", "Average daily value traded", "EGP"),
    "days_traded_90d": ("days_traded_90d", "Days traded (of last 90)", ""),
    "volatility_pct": ("volatility_pct", "Volatility", "%"),
    "max_drawdown_pct": ("max_drawdown_pct", "Worst fall", "%"),
    "ret_1y": ("ret_1y", "1-year return", "%"),
    "ret_3y": ("ret_3y", "3-year return", "%"),
    "valuation_confidence": ("valuation_confidence", "Valuation confidence", ""),
}

# Deliberately NOT filterable or sortable: the model's estimate of how far
# price sits from value.
#
# Sorting a list of companies by that number produces a ranked buy list
# generated by this platform, ordered by attractiveness. However the page is
# captioned, that is what it is, and it is the single feature most likely to be
# screenshotted and passed on with no method, no confidence score and no
# assumptions attached. The figure stays on each company's own page, where the
# range, the disagreement between methods and the calibration sit beside it.
WITHHELD_FROM_SCREENER = {
    "upside_pct": ("The gap between price and the model's estimate is shown on "
                   "each company's page, next to the range it came from and how "
                   "much the methods disagreed. It is not offered as a way to "
                   "rank companies, because a sorted list of it would be a "
                   "recommendation list without any of that context."),
}

SORTABLE = set(FILTERABLE) | {"ticker", "name"}


def run_screen(db, filters: list[dict], sort_by: str = "market_cap",
               descending: bool = True, sectors: list[str] | None = None,
               limit: int = 100, include_partial: bool = True) -> dict:
    """
    filters: [{"field": "roe_pct", "op": "gte", "value": 15}, ...]
    ops: gte | lte | gt | lt | eq
    """
    q = (select(Security, SecurityMetrics)
         .join(SecurityMetrics, SecurityMetrics.security_id == Security.id)
         .where(Security.listing_status == "listed"))
    if sectors:
        q = q.where(Security.sector.in_(sectors))
    if not include_partial:
        q = q.where(Security.data_quality == "full")

    rows = db.execute(q).all()

    used_fields = [f["field"] for f in filters if f.get("field") in FILTERABLE]
    kept, skipped_missing = [], 0

    for sec, m in rows:
        # A company must have every filtered metric to be judged fairly.
        missing = [f for f in used_fields if getattr(m, FILTERABLE[f][0]) is None]
        if missing:
            skipped_missing += 1
            continue

        ok = True
        for f in filters:
            field = f.get("field")
            if field not in FILTERABLE:
                continue
            val = getattr(m, FILTERABLE[field][0])
            try:
                target = float(f["value"])
            except (TypeError, ValueError, KeyError):
                continue
            op = f.get("op", "gte")
            if op == "gte" and not val >= target: ok = False
            elif op == "lte" and not val <= target: ok = False
            elif op == "gt" and not val > target: ok = False
            elif op == "lt" and not val < target: ok = False
            elif op == "eq" and not abs(val - target) < 1e-9: ok = False
            if not ok:
                break
        if ok:
            kept.append((sec, m))

    # Sort, pushing unknown sort keys to the end rather than treating them as 0.
    if sort_by == "ticker":
        kept.sort(key=lambda r: r[0].ticker, reverse=descending)
    elif sort_by == "name":
        kept.sort(key=lambda r: r[0].name_en, reverse=descending)
    else:
        col = FILTERABLE.get(sort_by, ("market_cap",))[0]
        kept.sort(key=lambda r: (getattr(r[1], col) is None,
                                 -(getattr(r[1], col) or 0) if descending
                                 else (getattr(r[1], col) or 0)))

    results = [_row(sec, m) for sec, m in kept[:limit]]

    return {
        "count": len(kept),
        "returned": len(results),
        "skipped_missing_data": skipped_missing,
        "universe_size": len(rows),
        "filters_applied": [
            {"field": f["field"], "label": FILTERABLE[f["field"]][1],
             "op": f.get("op", "gte"), "value": f["value"],
             "unit": FILTERABLE[f["field"]][2]}
            for f in filters if f.get("field") in FILTERABLE],
        "results": results,
        "note": ("%d companies were left out because at least one of the "
                 "measures you filtered on is not available for them. They are "
                 "not necessarily failing the test - we simply cannot check."
                 % skipped_missing) if skipped_missing else None,
    }


def _row(sec, m) -> dict:
    return {
        "ticker": sec.ticker, "name": sec.name_en, "sector": sec.sector,
        "data_quality": sec.data_quality,
        "price": m.price, "day_change_pct": m.day_change_pct,
        "market_cap": m.market_cap,
        "pe": m.pe, "pb": m.pb, "ps": m.ps, "ev_ebitda": m.ev_ebitda,
        "dividend_yield_pct": m.dividend_yield_pct,
        "roe_pct": m.roe_pct, "roa_pct": m.roa_pct, "roic_pct": m.roic_pct,
        "net_margin_pct": m.net_margin_pct,
        "operating_margin_pct": m.operating_margin_pct,
        "revenue_growth_pct": m.revenue_growth_pct,
        "revenue_cagr_3y_pct": m.revenue_cagr_3y_pct,
        "earnings_growth_pct": m.earnings_growth_pct,
        "debt_to_equity": m.debt_to_equity,
        "volatility_pct": m.volatility_pct,
        "max_drawdown_pct": m.max_drawdown_pct,
        "adtv_90d": m.adtv_90d,
        "days_traded_90d": m.days_traded_90d,
        "liquidity_band": m.liquidity_band,
        "ret_1y": m.ret_1y, "ret_3y": m.ret_3y, "ret_5y": m.ret_5y,
        # Model upside is intentionally absent -- see WITHHELD_FROM_SCREENER.
        "valuation_class": m.valuation_class,
        "valuation_confidence": m.valuation_confidence,
        "as_of": m.as_of.isoformat() if m.as_of else None,
    }


# ---------------------------------------------------------------------------
def compare(db, tickers: list[str]) -> dict:
    """
    Compare several companies across the same measures.

    Reports differences and says which company leads on each measure. It does
    NOT name an overall winner or suggest what to buy: which measures matter
    depends on the reader's own goals, and ranking them for the reader would be
    advice rather than research.
    """
    if len(tickers) < 2:
        raise ValueError("Choose at least two companies to compare.")
    if len(tickers) > 6:
        raise ValueError("Compare at most six companies at a time.")

    rows = []
    for t in tickers:
        r = db.execute(
            select(Security, SecurityMetrics)
            .join(SecurityMetrics, SecurityMetrics.security_id == Security.id)
            .where(Security.ticker == t.upper())).first()
        if r is None:
            raise ValueError("We do not hold data for '%s'." % t)
        rows.append(_row(r[0], r[1]))

    # (field, label, higher_is_better, unit)
    measures = [
        ("price", "Price", None, "EGP"),
        ("market_cap", "Market value", None, "EGP"),
        ("pe", "Price / earnings", False, "x"),
        ("pb", "Price / book", False, "x"),
        ("ev_ebitda", "EV / EBITDA", False, "x"),
        ("dividend_yield_pct", "Dividend yield", True, "%"),
        ("roe_pct", "Return on equity", True, "%"),
        ("roic_pct", "Return on invested capital", True, "%"),
        ("net_margin_pct", "Net margin", True, "%"),
        ("revenue_growth_pct", "Revenue growth", True, "%"),
        ("earnings_growth_pct", "Profit growth", True, "%"),
        ("debt_to_equity", "Debt / equity", False, "x"),
        ("volatility_pct", "Volatility", False, "%"),
        ("max_drawdown_pct", "Worst fall", True, "%"),
        ("ret_1y", "1-year return", True, "%"),
        ("ret_3y", "3-year return", True, "%"),
    ]

    table, observations = [], []
    for field, label, higher_better, unit in measures:
        vals = [(r["ticker"], r.get(field)) for r in rows]
        present = [(t, v) for t, v in vals if v is not None]
        leader = None
        if higher_better is not None and len(present) >= 2:
            leader = (max(present, key=lambda x: x[1])[0] if higher_better
                      else min(present, key=lambda x: x[1])[0])
        table.append({
            "field": field, "label": label, "unit": unit,
            "values": {t: v for t, v in vals},
            "leader": leader,
            "missing": [t for t, v in vals if v is None],
        })

    # A few plain-language observations, strictly factual.
    def _note(field, label, higher_better, fmt):
        present = [(r["ticker"], r.get(field)) for r in rows if r.get(field) is not None]
        if len(present) < 2:
            return
        best = (max(present, key=lambda x: x[1]) if higher_better
                else min(present, key=lambda x: x[1]))
        worst = (min(present, key=lambda x: x[1]) if higher_better
                 else max(present, key=lambda x: x[1]))
        if best[0] != worst[0]:
            observations.append(
                "%s: %s is at %s, against %s for %s."
                % (label, best[0], fmt % best[1], fmt % worst[1], worst[0]))

    _note("roe_pct", "Return on equity", True, "%.1f%%")
    _note("pe", "Price to earnings", False, "%.1fx")
    _note("dividend_yield_pct", "Dividend yield", True, "%.2f%%")
    _note("volatility_pct", "Volatility", False, "%.1f%%")
    _note("revenue_growth_pct", "Revenue growth", True, "%.1f%%")

    return {
        "companies": rows,
        "table": table,
        "observations": observations,
        "note": ("Leading on one measure does not make a company a better "
                 "investment. Which measures matter depends on what you are "
                 "trying to achieve, and that judgement is yours."),
    }
